# Generated by Django 5.2.13 on 2026-04-27 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(db_comment='申请中的店铺名称', max_length=100, verbose_name='店铺名称')),
                ('contact_name', models.CharField(db_comment='联系人姓名', max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(db_comment='联系人手机号', max_length=20, verbose_name='联系电话')),
                ('application_reason', models.CharField(blank=True, db_comment='申请说明，可为空', default='', max_length=255, verbose_name='申请说明')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], db_comment='审核状态：待审核、已通过、已拒绝', default='pending', max_length=20, verbose_name='审核状态')),
                ('review_remark', models.CharField(blank=True, db_comment='管理员审核备注，可为空', default='', max_length=255, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, db_comment='审核时间，可为空', null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='申请创建时间', verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='记录最后更新时间', verbose_name='更新时间')),
                ('reviewed_by', models.ForeignKey(blank=True, db_comment='执行审核的管理员，可为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_merchant_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(db_comment='提交商家申请的用户', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '商家申请',
                'verbose_name_plural': '商家申请',
                'db_table': 'merchant_application',
                'db_table_comment': '商家申请表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', '消费者'), ('merchant', '商家'), ('admin', '管理员')], db_comment='用户角色：消费者、商家、管理员', default='customer', max_length=20, verbose_name='角色')),
                ('nickname', models.CharField(blank=True, db_comment='用户昵称，可为空', default='', max_length=50, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, db_comment='用户手机号，可为空', default='', max_length=20, verbose_name='手机号')),
                ('avatar', models.URLField(blank=True, db_comment='用户头像 URL，可为空', default='', max_length=255, verbose_name='头像地址')),
                ('gender', models.CharField(blank=True, db_comment='用户性别，可为空', default='', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, db_comment='用户生日，可为空', null=True, verbose_name='生日')),
                ('address', models.CharField(blank=True, db_comment='用户默认收货地址，可为空', default='', max_length=255, verbose_name='默认地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='记录最后更新时间', verbose_name='更新时间')),
                ('user', models.OneToOneField(db_comment='关联 Django 内置用户表 auth_user', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
                'db_table': 'user_profile',
                'db_table_comment': '用户扩展信息表',
            },
        ),
    ]
