# Generated by Django 5.2.13 on 2026-04-27 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_comment='订单唯一编号', max_length=64, unique=True, verbose_name='订单编号')),
                ('status', models.CharField(choices=[('pending_payment', '待支付'), ('paid', '已支付'), ('shipped', '已发货'), ('completed', '已完成'), ('canceled', '已取消'), ('refunded', '已退款')], db_comment='订单状态：待支付、已支付、已发货、已完成、已取消、已退款', default='pending_payment', max_length=30, verbose_name='订单状态')),
                ('total_amount', models.DecimalField(db_comment='订单总金额', decimal_places=2, default=0, max_digits=10, verbose_name='订单总金额')),
                ('pay_amount', models.DecimalField(db_comment='用户实际支付金额', decimal_places=2, default=0, max_digits=10, verbose_name='实付金额')),
                ('receiver_name', models.CharField(db_comment='收货人姓名', max_length=50, verbose_name='收货人')),
                ('receiver_phone', models.CharField(db_comment='收货手机号', max_length=20, verbose_name='收货手机号')),
                ('receiver_address', models.CharField(db_comment='收货详细地址', max_length=255, verbose_name='收货地址')),
                ('remark', models.CharField(blank=True, db_comment='用户下单备注，可为空', default='', max_length=255, verbose_name='订单备注')),
                ('shipping_company', models.CharField(blank=True, db_comment='发货物流公司，可为空', default='', max_length=100, verbose_name='物流公司')),
                ('tracking_no', models.CharField(blank=True, db_comment='物流快递单号，可为空', default='', max_length=100, verbose_name='快递单号')),
                ('shipping_remark', models.CharField(blank=True, db_comment='物流备注说明，可为空', default='', max_length=255, verbose_name='物流备注')),
                ('paid_at', models.DateTimeField(blank=True, db_comment='订单支付时间，可为空', null=True, verbose_name='支付时间')),
                ('shipped_at', models.DateTimeField(blank=True, db_comment='订单发货时间，可为空', null=True, verbose_name='发货时间')),
                ('completed_at', models.DateTimeField(blank=True, db_comment='订单完成时间，可为空', null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='订单创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='订单最后更新时间', verbose_name='更新时间')),
                ('user', models.ForeignKey(db_comment='下单用户', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order_info',
                'db_table_comment': '订单主表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_comment='下单时的商品名称快照', max_length=200, verbose_name='商品名称快照')),
                ('product_image', models.URLField(blank=True, db_comment='下单时的商品主图快照', default='', max_length=255, verbose_name='商品图片快照')),
                ('product_price', models.DecimalField(db_comment='下单时的商品单价快照', decimal_places=2, max_digits=10, verbose_name='商品单价快照')),
                ('quantity', models.PositiveIntegerField(db_comment='购买数量', default=1, verbose_name='购买数量')),
                ('subtotal_amount', models.DecimalField(db_comment='当前明细小计金额', decimal_places=2, default=0, max_digits=10, verbose_name='小计金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间')),
                ('order', models.ForeignKey(db_comment='所属订单', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='订单')),
                ('product', models.ForeignKey(blank=True, db_comment='关联原始商品，可为空，防止商品删除后历史订单丢失', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 'order_item',
                'db_table_comment': '订单明细表',
            },
        ),
    ]
