# Generated by Django 5.2.13 on 2026-04-27 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='购物车创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='购物车最后更新时间', verbose_name='更新时间')),
                ('user', models.OneToOneField(db_comment='所属用户，一个用户对应一个购物车', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'cart',
                'db_table_comment': '购物车主表',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(db_comment='商品购买数量，最少为1', default=1, verbose_name='购买数量')),
                ('checked', models.BooleanField(db_comment='是否选中用于结算', default=True, verbose_name='是否选中')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='记录最后更新时间', verbose_name='更新时间')),
                ('cart', models.ForeignKey(db_comment='所属购物车', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='购物车')),
                ('product', models.ForeignKey(db_comment='加入购物车的商品', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车明细',
                'verbose_name_plural': '购物车明细',
                'db_table': 'cart_item',
                'db_table_comment': '购物车明细表',
                'constraints': [models.UniqueConstraint(fields=('cart', 'product'), name='uniq_cart_product')],
            },
        ),
    ]
