# Generated by Django 5.2.13 on 2026-04-27 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_comment='用户浏览该商品的时间', verbose_name='浏览时间')),
                ('product', models.ForeignKey(db_comment='被浏览的商品', on_delete=django.db.models.deletion.CASCADE, related_name='browse_histories', to='products.product', verbose_name='商品')),
                ('user', models.ForeignKey(db_comment='浏览商品的用户', on_delete=django.db.models.deletion.CASCADE, related_name='browse_histories', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览记录',
                'verbose_name_plural': '浏览记录',
                'db_table': 'browse_history',
                'db_table_comment': '商品浏览记录表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_comment='推荐来源，如热门推荐、同类推荐、浏览推荐等', default='manual', max_length=50, verbose_name='推荐来源')),
                ('score', models.DecimalField(db_comment='推荐分值，MVP 阶段可简单记录', decimal_places=2, default=0, max_digits=8, verbose_name='推荐分值')),
                ('remark', models.CharField(blank=True, db_comment='推荐原因说明', default='', max_length=255, verbose_name='推荐说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='推荐记录创建时间', verbose_name='创建时间')),
                ('product', models.ForeignKey(db_comment='被推荐的商品', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='products.product', verbose_name='商品')),
                ('user', models.ForeignKey(db_comment='被推荐商品的用户', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '推荐日志',
                'verbose_name_plural': '推荐日志',
                'db_table': 'recommendation_log',
                'db_table_comment': '推荐日志表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='用户收藏该商品的时间', verbose_name='收藏时间')),
                ('product', models.ForeignKey(db_comment='被收藏的商品', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='products.product', verbose_name='商品')),
                ('user', models.ForeignKey(db_comment='收藏商品的用户', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品收藏',
                'verbose_name_plural': '商品收藏',
                'db_table': 'favorite',
                'db_table_comment': '商品收藏表',
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='uniq_user_favorite_product')],
            },
        ),
    ]
