# Generated by Django 5.2.13 on 2026-04-27 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='商品分类名称，唯一', max_length=100, unique=True, verbose_name='分类名称')),
                ('sort_order', models.IntegerField(db_comment='分类排序值，越小越靠前', default=0, verbose_name='排序值')),
                ('is_active', models.BooleanField(db_comment='分类是否启用', default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='记录最后更新时间', verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, db_comment='父级分类，可为空，为空表示一级分类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'category',
                'db_table_comment': '商品分类表',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='商品名称', max_length=200, verbose_name='商品名称')),
                ('subtitle', models.CharField(blank=True, db_comment='商品副标题，可为空', default='', max_length=255, verbose_name='商品副标题')),
                ('brand', models.CharField(blank=True, db_comment='商品品牌，可为空', default='', max_length=100, verbose_name='品牌')),
                ('sku', models.CharField(db_comment='商品唯一 SKU 编码', max_length=100, unique=True, verbose_name='SKU编码')),
                ('price', models.DecimalField(db_comment='商品销售价格', decimal_places=2, max_digits=10, verbose_name='销售价格')),
                ('market_price', models.DecimalField(db_comment='商品划线价/市场价', decimal_places=2, default=0, max_digits=10, verbose_name='市场价格')),
                ('stock', models.PositiveIntegerField(db_comment='当前可售库存数量', default=0, verbose_name='库存数量')),
                ('low_stock_warning', models.PositiveIntegerField(db_comment='当库存小于等于该值时触发低库存提醒', default=10, verbose_name='低库存预警值')),
                ('sales_count', models.PositiveIntegerField(db_comment='商品累计销量', default=0, verbose_name='销量')),
                ('description', models.TextField(blank=True, db_comment='商品详情描述', default='', verbose_name='商品描述')),
                ('main_image', models.URLField(blank=True, db_comment='商品主图 URL，可为空', default='', max_length=255, verbose_name='主图地址')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('on_sale', '上架'), ('off_sale', '下架')], db_comment='商品状态：草稿、上架、下架', default='on_sale', max_length=20, verbose_name='商品状态')),
                ('is_recommend', models.BooleanField(db_comment='是否推荐到首页或推荐位', default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='记录最后更新时间', verbose_name='更新时间')),
                ('category', models.ForeignKey(db_comment='商品所属分类', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='商品分类')),
                ('merchant', models.ForeignKey(blank=True, db_comment='商品所属商家，可为空；MVP 阶段允许为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_products', to=settings.AUTH_USER_MODEL, verbose_name='商家')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'product',
                'db_table_comment': '商品主表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('increase', '入库'), ('decrease', '出库'), ('lock', '锁定库存'), ('unlock', '释放库存')], db_comment='库存变动类型：入库、出库、锁定、释放', max_length=20, verbose_name='变动类型')),
                ('change_quantity', models.IntegerField(db_comment='本次库存变动数量，可正可负', verbose_name='变动数量')),
                ('before_stock', models.IntegerField(db_comment='库存变动前的数量', default=0, verbose_name='变动前库存')),
                ('after_stock', models.IntegerField(db_comment='库存变动后的数量', default=0, verbose_name='变动后库存')),
                ('remark', models.CharField(blank=True, db_comment='库存变动备注说明', default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, db_comment='执行库存操作的用户，可为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('product', models.ForeignKey(db_comment='关联商品', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存日志',
                'verbose_name_plural': '库存日志',
                'db_table': 'inventory_log',
                'db_table_comment': '库存变动日志表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(db_comment='商品图片 URL', max_length=255, verbose_name='图片地址')),
                ('alt_text', models.CharField(blank=True, db_comment='图片说明文字，可为空', default='', max_length=100, verbose_name='图片说明')),
                ('sort_order', models.IntegerField(db_comment='图片排序值，越小越靠前', default=0, verbose_name='排序值')),
                ('is_main', models.BooleanField(db_comment='是否为主图', default=False, verbose_name='是否主图')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间')),
                ('product', models.ForeignKey(db_comment='所属商品', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 'product_image',
                'db_table_comment': '商品图片表',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
