# Generated by Django 5.2.13 on 2026-04-27 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(db_comment='支付记录唯一编号', max_length=64, unique=True, verbose_name='支付单号')),
                ('method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('mock', '模拟支付')], db_comment='支付方式：支付宝、微信、模拟支付', default='mock', max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('unpaid', '未支付'), ('success', '支付成功'), ('failed', '支付失败'), ('refunded', '已退款')], db_comment='支付状态：未支付、成功、失败、退款', default='unpaid', max_length=20, verbose_name='支付状态')),
                ('amount', models.DecimalField(db_comment='本次支付金额', decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('third_party_trade_no', models.CharField(blank=True, db_comment='第三方支付平台返回的交易号，可为空', default='', max_length=100, verbose_name='第三方交易号')),
                ('paid_at', models.DateTimeField(blank=True, db_comment='支付成功时间，可为空', null=True, verbose_name='支付时间')),
                ('remark', models.CharField(blank=True, db_comment='支付备注说明', default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='记录最后更新时间', verbose_name='更新时间')),
                ('order', models.OneToOneField(db_comment='关联订单，一个订单对应一条主要支付记录', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='订单')),
                ('user', models.ForeignKey(db_comment='支付用户', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payment',
                'db_table_comment': '支付记录表',
                'ordering': ['-id'],
            },
        ),
    ]
